server:
  port: 8082

spring:
  application:
    name: accounting-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/accounting_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
