spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: accounting-service
          uri: lb://ACCOUNTING-SERVICE
          predicates:
            - Path=/api/account/**
          filters:
            - JwtFilter

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
