server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/bank_db

security:
  jwt:
    secret: mySecretKey
    expiration: 3600000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
